# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - achievers

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read # Required for actions/checkout
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v6

      - name: Setup Node LTS Environment
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: "Resolve Project Dependencies Using Npm"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build
          npm run test --if-present
          npm prune --production
          popd

      - name: "Log in to Azure with AZ CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }} # Required to log in with OIDC
          tenant-id: ${{ vars.AZURE_TENANT_ID }} # Required to log in with OIDC
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }} # Required to log in with OIDC

      - name: "Run the Azure Functions action"
        uses: Azure/functions-action@v1
        id: deploy-to-function-app
        with:
          app-name: "achievers"
          slot-name: "Production"
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
